// <auto-generated />
using JewelryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JewelryShop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JewelryShop.Models.JewelryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("InStock")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Picture1")
                        .IsRequired();

                    b.Property<string>("Picture2");

                    b.Property<string>("Picture3");

                    b.Property<string>("Price")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("JewelryItem");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Expertly hand crafted earrings perfect for a night out",
                            InStock = "Yes - Limited",
                            Name = "Blue Earring Set",
                            Picture1 = "~/Assets/Set1.1.jpg",
                            Picture2 = "~/Assets/Set1.2.jpg",
                            Picture3 = "~/Assets/Set1.3.jpg",
                            Price = "50$"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
